In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
from dl85 import DL85Classifier
from sklearn.metrics import confusion_matrix, precision_score, f1_score
import os
import time

In [2]:
source_folder = "data/pydl8.5_datasets"
dest_folder = "data/pydl8.5_datasets_split"
log_filename = "dl85_py_result.txt"

In [10]:
data_files = os.listdir(source_folder)
with open(log_filename, 'a') as logfile:
    logfile.write("name, dl_accu, dl_f1, dl_time_elapsed, dl_accu_train \n")
for this_file in data_files:  
    filename_stem = this_file.split('.')[0]
    X_train = np.genfromtxt(dest_folder + "/" + filename_stem + "_X_train.txt", delimiter = " ")
    y_train = np.genfromtxt(dest_folder + "/" + filename_stem + "_y_train.txt", delimiter = " ")
    X_test = np.genfromtxt(dest_folder + "/" + filename_stem + "_X_test.txt", delimiter = " ")
    y_test = np.genfromtxt(dest_folder + "/" + filename_stem + "_y_test.txt", delimiter = " ")
    start_time = time.time()
    clf = DL85Classifier(max_depth = 3, min_sup=5, time_limit=360)
    clf.fit(X_train, y_train)
    end_time = time.time()
    time_elapsed = end_time - start_time
    y_pred = clf.predict(X_test)
    confmat = confusion_matrix(y_test, y_pred)
    TN = confmat[0][0]
    TP = confmat[1][1]
    FP = confmat[0][1]
    FN = confmat[1][0]
    f1 = TP/(TP+(FN+FP)/2)
    accu = (TP + TN)/(TP+TN+FP+FN)
    # get training accuracy
    y_pred = clf.predict(X_train)  # test on training
    confmat = confusion_matrix(y_train, y_pred)  # test on training
    TN = confmat[0][0]
    TP = confmat[1][1]
    FP = confmat[0][1]
    FN = confmat[1][0]
    f1_train = TP/(TP+(FN+FP)/2)
    accu_train = (TP + TN)/(TP+TN+FP+FN)
    with open(log_filename, 'a') as logfile:
        logfile.write(filename_stem + ', ' + "{:.5f}, {:.5f}, {:.2f}, {:.5f}".format(accu, f1, time_elapsed, accu_train) + '\n')


DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found


In [4]:
# Below is for rev2: each dataset run 20 times, with 70/30 split for train/test
source_folder = "data/pydl8.5_datasets"
dest_folder = "data/pydl8.5_datasets_split_20"
log_filename = "dl85_py_result_20.txt"

In [5]:
data_files = os.listdir(source_folder)
with open(log_filename, 'a') as logfile:
    logfile.write("name, batch, dl_accu, dl_f1, dl_time_elapsed, dl_accu_train \n")
for this_file in data_files:  
    filename_stem = this_file.split('.')[0]
    for k in range(1,21):
        X_train = np.genfromtxt(dest_folder + "/" + filename_stem + "_X_train_" + str(k) + ".txt", delimiter = " ")
        y_train = np.genfromtxt(dest_folder + "/" + filename_stem + "_y_train_" + str(k) + ".txt", delimiter = " ")
        X_test = np.genfromtxt(dest_folder + "/" + filename_stem + "_X_test_" + str(k) + ".txt", delimiter = " ")
        y_test = np.genfromtxt(dest_folder + "/" + filename_stem + "_y_test_" + str(k) + ".txt", delimiter = " ")
        start_time = time.time()
        # Default setting as suggested in the sample code of the companion paper of this DL85 package
        # All cases should be able to complete within 300 secs, give some slack to avoid capping in result log
        clf = DL85Classifier(max_depth = 3, min_sup=5, time_limit=360)  
        clf.fit(X_train, y_train)
        end_time = time.time()
        time_elapsed = end_time - start_time
        y_pred = clf.predict(X_test)
        confmat = confusion_matrix(y_test, y_pred)
        TN = confmat[0][0]
        TP = confmat[1][1]
        FP = confmat[0][1]
        FN = confmat[1][0]
        f1 = TP/(TP+(FN+FP)/2)
        accu = (TP + TN)/(TP+TN+FP+FN)
        # get training accuracy
        y_pred = clf.predict(X_train)  # test on training
        confmat = confusion_matrix(y_train, y_pred)  # test on training
        TN = confmat[0][0]
        TP = confmat[1][1]
        FP = confmat[0][1]
        FN = confmat[1][0]
        f1_train = TP/(TP+(FN+FP)/2)
        accu_train = (TP + TN)/(TP+TN+FP+FN)
        with open(log_filename, 'a') as logfile:
            logfile.write(filename_stem + ', ' + "{:d}, {:.5f}, {:.5f}, {:.2f}, {:.5f}".format(k, accu, f1, time_elapsed, accu_train) + '\n')


DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitt

DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitt

In [5]:
# Below is for rev3: set depth to 1, 2, 3
source_folder = "data/pydl8.5_datasets"
dest_folder = "data/pydl8.5_datasets_split_20"
log_filename = "dl85_py_result_20_depth2.txt"

In [6]:
data_files = os.listdir(source_folder)
with open(log_filename, 'a') as logfile:
    logfile.write("name, batch, dl_accu, dl_f1, dl_time_elapsed, dl_accu_train \n")
for this_file in data_files:  
    filename_stem = this_file.split('.')[0]
    for k in range(1,21):
        X_train = np.genfromtxt(dest_folder + "/" + filename_stem + "_X_train_" + str(k) + ".txt", delimiter = " ")
        y_train = np.genfromtxt(dest_folder + "/" + filename_stem + "_y_train_" + str(k) + ".txt", delimiter = " ")
        X_test = np.genfromtxt(dest_folder + "/" + filename_stem + "_X_test_" + str(k) + ".txt", delimiter = " ")
        y_test = np.genfromtxt(dest_folder + "/" + filename_stem + "_y_test_" + str(k) + ".txt", delimiter = " ")
        start_time = time.time()
        # Default setting as suggested in the sample code of the companion paper of this DL85 package
        # All cases should be able to complete within 300 secs, give some slack to avoid capping in result log
        clf = DL85Classifier(max_depth = 2, min_sup=5, time_limit=360)  
        clf.fit(X_train, y_train)
        end_time = time.time()
        time_elapsed = end_time - start_time
        y_pred = clf.predict(X_test)
        confmat = confusion_matrix(y_test, y_pred)
        TN = confmat[0][0]
        TP = confmat[1][1]
        FP = confmat[0][1]
        FN = confmat[1][0]
        f1 = TP/(TP+(FN+FP)/2)
        accu = (TP + TN)/(TP+TN+FP+FN)
        # get training accuracy
        y_pred = clf.predict(X_train)  # test on training
        confmat = confusion_matrix(y_train, y_pred)  # test on training
        TN = confmat[0][0]
        TP = confmat[1][1]
        FP = confmat[0][1]
        FN = confmat[1][0]
        f1_train = TP/(TP+(FN+FP)/2)
        accu_train = (TP + TN)/(TP+TN+FP+FN)
        with open(log_filename, 'a') as logfile:
            logfile.write(filename_stem + ', ' + "{:d}, {:.5f}, {:.5f}, {:.2f}, {:.5f}".format(k, accu, f1, time_elapsed, accu_train) + '\n')


DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitt

DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitting: Solution found
DL8.5 fitt

In [17]:
# test the loop content
filename_stem = "hepatitis"
X_train = np.genfromtxt(dest_folder + "/" + filename_stem + "_X_train.txt", delimiter = " ")
y_train = np.genfromtxt(dest_folder + "/" + filename_stem + "_y_train.txt", delimiter = " ")
X_test = np.genfromtxt(dest_folder + "/" + filename_stem + "_X_test.txt", delimiter = " ")
y_test = np.genfromtxt(dest_folder + "/" + filename_stem + "_y_test.txt", delimiter = " ")
clf = DL85Classifier(max_depth = 3, min_sup=10)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
confmat = confusion_matrix(y_test, y_pred)
TN = confmat[0][0]
TP = confmat[1][1]
FP = confmat[0][1]
FN = confmat[1][0]
f1 = TP/(TP+(FN+FP)/2)
accu = (TP + TN)/(TP+TN+FP+FN)
# get training accuracy
y_pred = clf.predict(X_train)  # test on training
confmat = confusion_matrix(y_train, y_pred)  # test on training
TN = confmat[0][0]
TP = confmat[1][1]
FP = confmat[0][1]
FN = confmat[1][0]
f1_train = TP/(TP+(FN+FP)/2)
accu_train = (TP + TN)/(TP+TN+FP+FN)

DL8.5 fitting: Solution found


In [5]:
confusion_matrix(y_test, y_pred)

array([[50,  0],
       [ 3, 12]])

In [18]:
accu, accu_train

(0.7857142857142857, 0.8947368421052632)

In [15]:
TN = confmat[0][0]
TP = confmat[1][1]
FP = confmat[0][1]
FN = confmat[1][0]
f1 = TP/(TP+(FN+FP)/2)
f1

0.9238578680203046

In [11]:
f1_score(y_test, y_pred)

0.9238578680203046

In [28]:
X = dataset[:, 1:]
y = dataset[:, 0]
#X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.00001,random_state=0)
X_train = X
y_train = y
clf = DL85Classifier(max_depth=3, min_sup=5)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_train)

DL8.5 fitting: Solution found


In [29]:
confusion_matrix(y_train, y_pred)

array([[ 94,  93],
       [ 19, 606]])

In [30]:
precision_score(y_train, y_pred)

0.8669527896995708

In [27]:
X_test

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0.,
        1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0.]])